she_codes_news/news/urls.py
# news/urls.py
from django.urls import path
from . import views
from users import urls

app_name = 'news'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('<int:pk>/comment', views.AddCommentView.as_view(), name='addComment')]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, UserProfile

app_name = 'users'
urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    # try to create a profile page 3 December, 9 December: 
    path('user-profile/<int:pk>/', UserProfile.as_view(), name='userProfile'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    # Changed this from .DateTimeField to .DateField to remove the time on articles. Needed to remember to makemigrations
    pub_date = models.DateField()
    content = models.TextField()
    image = models.URLField(null=True, blank=True)


# Class created for comments

class Comment(models.Model):
    post = models.ForeignKey(NewsStory, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

she_codes_news/users/models.py
# Create your models here.

from django.contrib.auth.models import AbstractUser
from django.db import models
# from news.models import NewsStory

# # Started to make class User Profile
# from django.db import models
# from django.contrib.auth.models import User

class CustomUser(AbstractUser):
    bio = models.TextField(max_length=500, blank = True, null = True)
    # posts = models.ForeignKey(NewsStory, related_name='author', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.username

she_codes_news/news/forms.py
# Django classes we need
from django import forms
from django.forms import ModelForm
from .models import NewsStory
from .models import Comment

# Form for submitting a story
class StoryForm(ModelForm):
    class Meta:
        model = NewsStory
        fields = ['title', 'pub_date', 'image', 'content']
        widgets = {
            'pub_date': forms.DateInput(
                format='%d/%m/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

# Form for submitting a comment
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets = {
            'date_added': forms.DateInput(
                format='%d/%m/%Y',
                attrs={
                    'class':'form-control',
                    'placeholder':'Select a date',
                    'type':'date'
                }
            ),
        }

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory, Comment
from .forms import StoryForm, CommentForm
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404




class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by("-pub_date",)[4:]
# the slice of stories needs to exclude the first 4 stories because they are showing up in the latest stories section without repeating the stories from the latest section. 

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by("-pub_date",)[:4]
        return context
    # Here the  [:4] slice and negative pub_date allow for a snapshot of the latest four stories to show up in reverse chronological order (newest to oldest)

# use getcontextdata. see line 20, change line 22
class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context
    

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    template_name = 'news/createStory.html'
    context_object_name = 'storyform'
    success_url = reverse_lazy('news:index')

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            # Redirect to create account or login page
            return redirect('login') 
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
# Adding a view for comments form on the page, rather than opening a new page 12 Dec
class AddCommentView(generic.CreateView):
    form_class = CommentForm
    template_name = 'news/story.html'
    context_object_name = 'commentform'

    # a function to allow the URL to go to the right page
    def get_success_url(self):
        return reverse_lazy('news:story', kwargs={'pk':self.kwargs.get("pk")}) 
    
    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.instance.post = get_object_or_404(NewsStory, pk=pk)
        return super().form_valid(form)

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm
from news.models import NewsStory



class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

#Detail view for User Profile
class UserProfile(generic.DetailView):
    model = CustomUser
    template_name = 'users/userProfile.html'
    context_object_name = 'user_stories'

    def get_queryset(self):
        '''Return user news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user_stories'] = NewsStory.objects.filter(author_id=self.kwargs['pk']).order_by("-pub_date",).all()
        return context

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}
{% block content %}
<br><br>
<form action="" method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/index.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}" />
{% endblock %}

{% block content %}
<section class="sectioncontent">

    <br><br>
    <h2>Latest News</h2>
    <div id="latest-stories">
        {% if latest_stories %}
        {% for story in latest_stories %}

        {% include "./storyCard.html" with story=story position=forloop.counter %}
        {% endfor %}
        {% else %}
        <p>No stories are available.</p>
        {% endif %}
    </div>
    <br><br>
    <h2>All News</h2>
    <div id="all-stories">
        {% if latest_stories %}
        {% for story in all_stories %}

        {% include "./storyCard.html" with story=story %}
        {% endfor %}
        {% else %}
        <p>No stories are available.</p>
        {% endif %}
    </div>
    {% endblock %}
</section>

she_codes_news/news/templates/news/story.html
<!-- news/templates/news/story.html -->
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css'%}" />
{% endblock %}

{% block content %}
<!-- {% debug %} -->
<section class="sectioncontent" id="story-wrapper">
  <h2>{{ story.title }}</h2>
  <h3>{{ story.author }}</h3>
  <section id="story-content">
    {%if story.image %}
    <img src="{{ story.image }}">
    {% else %}
    <img src="{% static '/news/images/placeholder-5.jpg'%}">
    {% endif %}

    {{ story.content|linebreaks }}
  </section>

  <!-- Adding in comments to articles Sun 10 Dec. Currently working. Next step 12 Dec to build button and form to add comment-->
  <h2>Comments</h2>
  <br />
  {% if not story.comments.all %}
  <h3>No comments </h3>
  {% else %}
  {% for comment in story.comments.all %}
  <strong>
    <h3>
      {{ comment.name }} -
      {{ comment.date_added}}
    </h3>
  </strong>
  <br />
  <p>{{ comment.body }}</p>
  <br /><br />
  {% endfor %}

  {% endif %}
</section>

<form class="commentform" action="{% url 'news:addComment' story.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="submit">
</form>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
  <a href="{% url 'news:story' story.id %}">
    {% if story.image %}
        <img src="{{ story.image }}" >
    {% else %}
          <img src="https://picsum.photos/600">
    {% endif %}
    <div class="story-card-text">
          <h3>{{ story.title }}</h3>
          <h4>{{ story.author }}</h4>
          <h4>{{ story.pub_date }}</h4>
      </div>
  </a>
</div>

she_codes_news/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title id="titletext">She Codes News</title>
    <meta name="description" content="" />
    <meta name="author" content="Goya Zheng" />
    <link
      href="https://fonts.googleapis.com/css?
family=Manjari&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}" />
    {% block stylesheets %}{% endblock %}
  </head>
  <body>
    <header>
      <div id="header-text">
        <a id="header-link" href="{% url 'news:index' %}">
          <h1>She {Codes} News</h1>
        </a>
      </div>
      {% include './nav.html' %}
    </header>
    {% load static %}
    <img src="{% static 'SheCodes-news-banner.png' %}" alt="AI generated images of women in the style of an Archie comic from the 1950s coding, meeting, and typing">

    {% block content %}{% endblock %}
  </body>
</html>

she_codes_news/templates/nav.html
<div id="box">
    <nav>
        <a href="{% url 'news:index' %}">Home</a>
        <a href="{% url 'users:createAccount' %}">Join Us</a>
        {% if request.user.is_authenticated %}
        <a href="{% url 'news:newStory' %}">Write New Story</a>
        <a href="{% url 'users:userProfile' user.id %}">Profile: {{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </nav>
</div>

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<section class="contentpage">
    <h2>Create Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create Account</button>
    </form>
</section>
{% endblock %}

she_codes_news/users/templates/users/userProfile.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<section class="contentpage">

  <h2 class="contenth2">Welcome {{user.username}}</h2>
  <section class="buttons">
    <a class="writestorybutton" href="{% url 'news:newStory' %}">Write New Story</a> <br>
    <a class="writestorybutton" href="#">Edit Account</a>
    <a class="writestorybutton" href="{% url 'users:createAccount' %}">Create New Account</a>
    <a class="writestorybutton" href="#">Delete Account</a>
  </section>

  <section>Bio ?! {{user.bio}}</section>

  <h2>{{user.username}}'s stories</h2>

  <!-- Trying to add in the user stories -->

  <div class="user-stories">
    <!-- upate latest stories to something else which makes more sense for naming -->
    {% if user_stories %}
    <!-- loop through variable which makes more sense -->
    {% for story in user_stories %}
    {% include "news/storyCard.html" with story=story %}
    {% endfor %}
    {% else %}
    <p>No stories are available.</p>
    {% endif %}
  </div>

  {% endblock %}

</section>